# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '1'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: '**/*.csproj'
    versioningScheme: byPrereleaseNumber
    verbosityPack: minimal
    packagesDirectory: '$(Build.ArtifactStagingDirectory)'
    requestedMajorVersion: 1
    requestedMinorVersion: 1
    requestedPatchVersion: 0
- task: NuGetCommand@2
  inputs:
    command: push
    allowPackageConflicts: true
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: 'https://pkgs.dev.azure.com/englishlearning-study/_packaging/english_learning_nuget/nuget/v3/index.json'
