# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: BuildAndAnalyze
        displayName: Build And Analyze
        pool:
          vmImage: 'windows-latest'
        variables:
          buildConfiguration: 'Release'
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              feedsToUse: 'select'
          - task: SonarQubePrepare@4
            inputs:
              SonarQube: 'sonarqube'
              scannerMode: 'MSBuild'
              projectKey: 'EnglishLearning.Utilities'
              projectName: 'EnglishLearning.Utilities'
              extraProperties: |
                sonar.sources="$(System.DefaultWorkingDirectory)/_LytvyniukDima_EnglishLearning.Utilities/."
                sonar.projectbasedir="$(System.DefaultWorkingDirectory)/_LytvyniukDima_EnglishLearning.Utilities/."
          - task: MSBuild@1
            inputs:
              solution: '**/*.sln'
          - task: SonarQubeAnalyze@4
          - task: SonarQubePublish@4
            inputs:
              pollingTimeoutSec: '300'

  - stage: Publish
    displayName: Publish Artifacts
    jobs:
      - job: PackAndPublish
        displayName: Pack And Publish
        pool:
          vmImage: 'Ubuntu-16.04'
        variables:
          buildConfiguration: 'Release'
          Major: '1'
          Minor: '1'
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: pack
            projects: '**/*.csproj'
            versioningScheme: byPrereleaseNumber
            verbosityPack: minimal
            packagesDirectory: '$(Build.ArtifactStagingDirectory)'
            requestedMajorVersion: 1
            requestedMinorVersion: 1
            requestedPatchVersion: 0
        - task: NuGetCommand@2
          inputs:
            command: push
            allowPackageConflicts: true
            searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            feedPublish: 'english_learning_nuget'
