# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '1'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: pack
    versioningScheme: byBuildNumber
    versionEnvVar: $(Major).$(Minor).$(Rev:r)
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    allowPackageConflicts: true
    feedPublish: "https://pkgs.dev.azure.com/englishlearning-study/_packaging/english_learning_nuget/nuget/v3/index.json"

